### ISSUE TITLE
[1.1.104] Patch seems successful, but no achievements granted

### ISSUE THREAD

**Issue by Aussiemon** [oorzkws/FactorioAchievementEnabler#12]
Log: [out.txt](https://github.com/oorzkws/FactorioAchievementEnabler/files/14382809/out.txt)

Using the latest version from Releases. The patch seems successful according to the log, but achieving "Logistics network embargo", "Steam all the way", and "Raining bullets" at the same time by finishing the game did not grant Steam achievements. No console was used.

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/13663574/bf813cbc-c009-4ecb-995a-e1cc67f69f5c)

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/13663574/a4c54bb6-3005-4465-8ce3-23ea4ccc384d)

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/13663574/2152c15b-ce8f-444e-bbba-c25287caf66c)

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/13663574/821a5948-947a-436b-800a-76ac7258748e)

[Rampant Deathrail - Win.zip](https://github.com/oorzkws/FactorioAchievementEnabler/files/14382842/Rampant.Deathrail.-.Win.zip)

**Comment by Aussiemon** [comment]
Different issue from #10 . Restarting my PC had no effect.

**Comment by oorzkws** [comment]
If you add a a steam_appid.txt with the content `427520` to the Factorio\bin\x64 folder and launch from the .exe instead of Steam, does it work?

**Comment by Aussiemon** [comment]
> If you add a a steam_appid.txt with the content `427520` to the Factorio\bin\x64 folder and launch from the .exe instead of Steam, does it work?

I no longer see "This is a modded save" at the top of the Achievements pane, so this might've worked!

**Comment by oorzkws** [comment]
> I no longer see "The game is modded" at the top of the Achievements pane, so this might've worked!

Good to hear it. You added the launch arguments from the instructions to your steam setup, correct?

**Comment by Aussiemon** [comment]
Removing the appid file and adding the launch options seems to be working. The achievements pane is still missing the modded dialogue. Thanks!

**Comment by oorzkws** [comment]
> Ah, I see the issue. I was following the instructions at [this post](https://forums.factorio.com/viewtopic.php?t=100924), but I didn't drill down into the comments to see the posted launch options fix. Removing the appid file and adding the launch options seems to be working. The achievements pane is still missing the modded dialogue. Thanks!

Thanks for the reminder, I edited the post.
