### ISSUE TITLE
Failed to patch only 3 of 6.

### ISSUE THREAD

**Issue by pongmagic** [oorzkws/FactorioAchievementEnabler#14]
Hey there, I just tried to install the patch, and it appears that the failed to patch 3 of 6 might still be an issue.  I made sure to install v1.0.6 which even [references that this issue has been fixed.](https://github.com/oorzkws/FactorioAchievementEnabler/issues/9).

See below for my log, and feel free to reach out if you need any additional information.  Thank you!
[out.txt](https://github.com/oorzkws/FactorioAchievementEnabler/files/15049833/out.txt)

**Comment by oorzkws** [comment]
Hey sorry for the late reply, this looks to be new as of 1.1.107. I'll refer you to #13 which I'll be working on shortly. 

Thanks!
