### ISSUE TITLE
This doesn't seem to be loading properly

### ISSUE THREAD

**Issue by ER-95** [oorzkws/FactorioAchievementEnabler#15]
Hi,

Is there any way to verify that this mod is actually loading properly? Running the output command gives me a file that is 0kb, and my achievements.dat file doesn't seem to update - only my achievements-modded.dat.

Many thanks

**Comment by oorzkws** [comment]
The "this game is modded" warning on the achievements window should disappear. Are you playing through steam or standalone (downloaded from Wube)?

**Comment by ER-95** [comment]
@oorzkws I'm playing through Steam, I've set up the launch command as it should be.

**Comment by oorzkws** [comment]
These are the steps I followed to create a log, please let me know if they work for you.

- Press Windows Key (beside Alt) + R together
- Type `cmd` in the run box and press OK
- in the command prompt, type `cd /d "C:\Path\To\Your\Factorio\Folder\bin\x64"` where you've replaced the path with your Factorio location and press enter
- in the command prompt, type `echo 427520 > steam_appid.txt` and press enter
- in the command prompt type `factorio.exe > out.txt` and press enter
- Let Factorio load, then exit Factorio
- Open your factorio folder and check the `out.txt` file contents and upload here if necessary

Let me know if those instructions produce a file for you. I've attached screenshots showing the cmd window after I've followed the steps and the log file as it shows for me.

![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/65210810/1068ef18-a09e-4ede-9b0d-c14b5a3c6a0a)
![image](https://github.com/oorzkws/FactorioAchievementEnabler/assets/65210810/9834a191-a774-4ca3-96ba-f0793b3d52cb)

**Comment by oorzkws** [comment]
I'm going to close this as there hasn't been further follow-up. Please comment or open a new issue if you continue to encounter problems.
