### ISSUE TITLE
update for 2.0/Space Age ?

### ISSUE THREAD

**Issue by xor50** [oorzkws/FactorioAchievementEnabler#20]
Hi!
I assume you know already, but on monday (11h UTC) the big **2.0 update** and the **Space Age expansion** will hit.
Those will also add new achievements.

This post should be two things:
1. a reminder, if you are not aware of that happening and
2. a question: When do think can you update? Do you need help, like do you need a log or something to make updating this easier? I have no idea, I just want to use it as soon as it's possible so if I can accelerate that with doing a test for you or something...

Thanks for you work! I'm really happy this tool exists.

**Comment by oorzkws** [comment]
Hi xor50,

Thanks for the kind words. I have Space Age compatibility completed, but I'm uncertain if it'll work with the non-expansion factorio.exe, as they're supposed to be different binaries now. I will verify that after launch, but if you're playing Space Age, the newest release should work for you.

https://github.com/oorzkws/FactorioAchievementEnabler/releases/latest

**Comment by oorzkws** [comment]
Just another note saying 1.0.10 is out and tested against the standalone and non-expansion releases now as well
