### ISSUE TITLE
Not working with 2.0.11

### ISSUE THREAD

**Issue by EITS-TE** [oorzkws/FactorioAchievementEnabler#22]
I just tried it, Steam Factorio DLC SA version 2.0.11, some mods
Copied current version.dll to C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64, modified start cmd line in Steam
Started fresh game (didn't use console commands), build first assembler, received the "Automate it" achievement in game, but not on steam.

Output from log looks good, see attachment

[startlog.txt](https://github.com/user-attachments/files/17530702/startlog.txt)

**Comment by xor50** [comment]
Yes, noticed that as well! I think they changed how nuclear power achievement was unlocked, maybe that's related. Coincidentally that was the exact achievement I noticed the issue with.

**Comment by rob-katt** [comment]
Ditto this, can also add that the achievements tab in game doesn't say that its modded

**Comment by SquidWhisperer** [comment]
Same issue here. Tried verifying and reinstalling file, no change. Did not get achievement for researching with yellow science.

**Comment by JJack407** [comment]
Same issue here, save working with achievements before 2.0.11 update. Updated and didn't get achievement for military science

**Comment by DylanSchneiderman** [comment]
Also am not getting achievements on steam - I finally plopped down a solar panel and didn't get the achievement. Tried putting in my first quality module, got the achievement in game but not in steam

**Comment by Sky-Tsamsiyu** [comment]
Same issue here, i've putting quality module in assembler and unlock ingame achievement but nothing on steam. I've try too with production science achievement and this is the same

**Comment by Sky-Tsamsiyu** [comment]
So, I don't know how it works, and I tried a lot of things but the Steam achievements unlock once you re-enter the main menu. 
I think I did something like this;

- I made a backup of my save with a different name
- I quit the game
- I deleted version.dll in the factorio folder
- I deleted the command line in the startup option
- I launched the game and disabled the mod
- (game auto-relaunch)
- Launch the save game (hit load when ask)
- I've save again with different name
- quit the game
- Re-put latest version.dll in factorio folder
- Re-put command line in start option
- Re-synchronyse mod with the save
- (game auto-relaunch)

Here, achievements i 've not unlocked before when are back after game starting (quality module and production science for me)

Absolutly don't know how it's work, juste a share \o/

**Comment by datasone** [comment]
2.0.11 changes a bit code which causes the patch to be invalid, I've tested and filed a pr on it.
If you want to test it out before the author reviews and releases a new dll, you can try mine temporary build: 
[version.dll_2.0.11_temp.zip](https://github.com/user-attachments/files/17534021/version.dll_2.0.11_temp.zip)

**Comment by Gormaz** [comment]
Tried the temp dll, worked perfectly for me, I just had to load up the game on the main menu for my achivements to unlock
Thanks for that!

**Comment by ihartsnape** [comment]
The temp dll worked for me as well!

**Comment by SquidWhisperer** [comment]
Temp dll also worked for me, thanks!

**Comment by Blackraz0r** [comment]
> 2.0.11 changes a bit code which causes the patch to be invalid, I've tested and filed a pr on it. If you want to test it out before the author reviews and releases a new dll, you can try mine temporary build: [version.dll_2.0.11_temp.zip](https://github.com/user-attachments/files/17534021/version.dll_2.0.11_temp.zip)

![image](https://github.com/user-attachments/assets/8f8cbe8f-9b2c-4b5e-a991-8731b1a47d5d)

ummm....

**Comment by LennoxP90** [comment]
i chose to build the DLL myself, I don't trust a random comment zip

**Comment by datasone** [comment]
> ![image](https://private-user-images.githubusercontent.com/26622216/380516423-8f8cbe8f-9b2c-4b5e-a991-8731b1a47d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODA1MTgsIm5iZiI6MTczMDA4MDIxOCwicGF0aCI6Ii8yNjYyMjIxNi8zODA1MTY0MjMtOGY4Y2JlOGYtOWIyYy00YjVlLWE5OTEtODczMWIxYTQ3ZDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAxNTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTJiZjI0N2JmNDg3ODI1ODliN2Q0ZDA5YWVhYzgxZjlmYjVkMzMyZmJkZmZmODZiNzc5MmJiZTMwNDlmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ttpv5vVD6ywsr48O7YrICM3owlS4n7qljpOGYPDmD7o)
> 
> ummm....

I think it may due to the dll itself hooking on other programs (i.e. the game), you can check it on virustotal, or just build with the source code in #23 if you have further concerns.

**Comment by rob-katt** [comment]
> 2.0.11 changes a bit code which causes the patch to be invalid, I've tested and filed a pr on it. If you want to test it out before the author reviews and releases a new dll, you can try mine temporary build: [version.dll_2.0.11_temp.zip](https://github.com/user-attachments/files/17534021/version.dll_2.0.11_temp.zip)

what did you use to compile it? seeing as the files is a whooping 20kb larger with barely any changes?

**Comment by datasone** [comment]
> > 2.0.11 changes a bit code which causes the patch to be invalid, I've tested and filed a pr on it. If you want to test it out before the author reviews and releases a new dll, you can try mine temporary build: [version.dll_2.0.11_temp.zip](https://github.com/user-attachments/files/17534021/version.dll_2.0.11_temp.zip)
> 
> what did you use to compile it? seeing as the files is a whooping 20kb larger with barely any changes?

VS Build Tools v143 (upgraded from v140 specified in project files, as I don't want to install another version) with x64 release profile, I think the upgraded build tools version may be the difference (e.g. more optimization where functions are chosen to be inlined)

**Comment by dat-guy-defoe** [comment]
Temp dll also worked for me, thanks!

**Comment by oorzkws** [comment]
Resolved in the latest release, thank you @datasone https://github.com/oorzkws/FactorioAchievementEnabler/releases/latest
