### ISSUE TITLE
Graphics from AAI Loaders

### ISSUE THREAD

**Issue by LennoxP90** [oorzkws/FactorioAchievementEnabler#24]
I like the look of AAI loaders but i do not like having to put lubricant in them, I see there is a graphics only option for that mod is it possible to replace the graphics of this mod with that one?
https://mods.factorio.com/mod/aai-loaders

**Comment by BLARGoMATIC** [comment]
wrong place to ask that.

This isn't a mod, it's a .dll for enabling steam achievements. No one can help you here.

**Comment by LennoxP90** [comment]
woops wrong github lmao
