### ISSUE TITLE
1.0.12 not working with factorio 2.0.12

### ISSUE THREAD

**Issue by Ioney** [oorzkws/FactorioAchievementEnabler#26]
```Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\Factorio\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 41943028]: 00007ff6772f0000 ~ 00007ff679aefff4
Apply Patch at 00007ff677482ad9
Patched 1 of 9.
RuleSize: 32		ReplSize: 4
Search range[size: 41943008]: 00007ff6772f0000 ~ 00007ff679aeffe0
Apply Patch at 00007ff6774633da
Patched 2 of 9.
RuleSize: 10		ReplSize: 4
Search range[size: 41943030]: 00007ff6772f0000 ~ 00007ff679aefff6
Apply Patch at 00007ff677463333
Patched 3 of 9.
RuleSize: 18		ReplSize: 8
Search range[size: 41943022]: 00007ff6772f0000 ~ 00007ff679aeffee
Apply Patch at 00007ff677992459
Patched 4 of 9.
RuleSize: 13		ReplSize: 7
Search range[size: 41943027]: 00007ff6772f0000 ~ 00007ff679aefff3
Apply Patch at 00007ff6780c4eeb
Patched 5 of 9.
RuleSize: 23		ReplSize: 11
Search range[size: 41943017]: 00007ff6772f0000 ~ 00007ff679aeffe9
Apply Patch at 00007ff6775ab729
Apply Patch at 00007ff6780c3140
Patched 6 of 9.
RuleSize: 23		ReplSize: 15
Search range[size: 41943017]: 00007ff6772f0000 ~ 00007ff679aeffe9
Apply Patch at 00007ff6780c31d9
Patched 7 of 9.
RuleSize: 14		ReplSize: 14
Search range[size: 41943026]: 00007ff6772f0000 ~ 00007ff679aefff2
Apply Patch at 00007ff6780c3330
Patched 8 of 9.
RuleSize: 15		ReplSize: 13
Search range[size: 41943025]: 00007ff6772f0000 ~ 00007ff679aefff1
Apply Patch at 00007ff677ce8aeb
Patched 9 of 9.
   0.000 Initializing Steam API.
   0.000 Steam requires game restart, restarting...
All done.
==============================================
```

**Comment by oorzkws** [comment]
Hi, 2.0.13 is current. Can you let me know if that works for you?

**Comment by oorzkws** [comment]
Rolled back to 2.0.12 without issue. I'll try the non-SA build
```
szExePath: C:\Games\Factorio\bin\x64\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 41943028]: 00007ff744830000 ~ 00007ff74702fff4
Apply Patch at 00007ff7449c2ad9
Patched 1 of 7.
RuleSize: 20		ReplSize: 8
Search range[size: 41943020]: 00007ff744830000 ~ 00007ff74702ffec
Apply Patch at 00007ff7449a33df
Apply Patch at 00007ff744aeb72c
Apply Patch at 00007ff745603143
Apply Patch at 00007ff7456031e0
Patched 2 of 7.
RuleSize: 10		ReplSize: 4
Search range[size: 41943030]: 00007ff744830000 ~ 00007ff74702fff6
Apply Patch at 00007ff7449a3333
Patched 3 of 7.
RuleSize: 18		ReplSize: 8
Search range[size: 41943022]: 00007ff744830000 ~ 00007ff74702ffee
Apply Patch at 00007ff744ed2459
Patched 4 of 7.
RuleSize: 13		ReplSize: 7
Search range[size: 41943027]: 00007ff744830000 ~ 00007ff74702fff3
Apply Patch at 00007ff745604eeb
Patched 5 of 7.
RuleSize: 14		ReplSize: 14
Search range[size: 41943026]: 00007ff744830000 ~ 00007ff74702fff2
Apply Patch at 00007ff745603330
Patched 6 of 7.
RuleSize: 15		ReplSize: 13
Search range[size: 41943025]: 00007ff744830000 ~ 00007ff74702fff1
Apply Patch at 00007ff745228aeb
Patched 7 of 7.
   0.000 Initializing Steam API.
   0.000 2024-10-31 20:09:45; Factorio 2.0.12 (build 79795, win64, steam, space-age)
   ```

**Comment by LennoxP90** [comment]
maybe im dumb but how can you tell it failed based on the logs

**Comment by oorzkws** [comment]
> maybe im dumb but how can you tell it failed based on the logs

Each set should patch one thing, except patch 2 which patches 4. If that doesn't match, something's not working.

**Comment by LennoxP90** [comment]
i find it interesting that the OP has everything patched but there is 9 and yours has only 7

**Comment by oorzkws** [comment]
Oh yeah, you pointed out something that I missed. They're not on the version of the achievement enabler they state they're on.

**Comment by LennoxP90** [comment]
I suggest you log out the version probably would make it a little easier to debug

**Comment by oorzkws** [comment]
Yeah, I don't actually keep the version in the binary right now, it was one more revision to do (I did not expect to have a userbase). That's a good reason for doing so.

**Comment by Ioney** [comment]
v1.0.12 with factorio 2.0.13:
```
Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\Factorio\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 41943028]: 00007ff76cb90000 ~ 00007ff76f38fff4
Apply Patch at 00007ff76cd22ad9
Patched 1 of 7.
RuleSize: 20		ReplSize: 8
Search range[size: 41943020]: 00007ff76cb90000 ~ 00007ff76f38ffec
Apply Patch at 00007ff76cd033df
Apply Patch at 00007ff76ce4b72c
Apply Patch at 00007ff76d963143
Apply Patch at 00007ff76d9631e0
Patched 2 of 7.
RuleSize: 10		ReplSize: 4
Search range[size: 41943030]: 00007ff76cb90000 ~ 00007ff76f38fff6
Apply Patch at 00007ff76cd03333
Patched 3 of 7.
RuleSize: 18		ReplSize: 8
Search range[size: 41943022]: 00007ff76cb90000 ~ 00007ff76f38ffee
Apply Patch at 00007ff76d232459
Patched 4 of 7.
RuleSize: 13		ReplSize: 7
Search range[size: 41943027]: 00007ff76cb90000 ~ 00007ff76f38fff3
Apply Patch at 00007ff76d964eeb
Patched 5 of 7.
RuleSize: 14		ReplSize: 14
Search range[size: 41943026]: 00007ff76cb90000 ~ 00007ff76f38fff2
Apply Patch at 00007ff76d963330
Patched 6 of 7.
RuleSize: 15		ReplSize: 13
Search range[size: 41943025]: 00007ff76cb90000 ~ 00007ff76f38fff1
Apply Patch at 00007ff76d588aeb
Patched 7 of 7.
   0.000 Initializing Steam API.
   0.000 Steam requires game restart, restarting...
All done.
==============================================

```

right before posting last night i unlocked "Rush to space" and "Logistic network embargo" but now i dont get the achievement on steam. i have a savegame right before researching my first fulgora research.

i kept 2.0.11 the last couple days because steam achievements worked with 1.0.11
then i updated to 2.0.12 with 1.0.12 patches and played until i unlocked the above mentioned achievements but steam did not recognize them. maybe the steam achievement doesnt get triggered because i already earned it ingame?

**Comment by X3n0n3x** [comment]
> i kept 2.0.11 the last couple days because steam achievements worked with 1.0.11 then i updated to 2.0.12 with 1.0.12 patches and played until i unlocked the above mentioned achievements but steam did not recognize them. maybe the steam achievement doesn't get triggered because i already earned it ingame?

The Steam achievements should unlock retroactively, or at least for those ones in particular based on me being in almost the same situation earlier this week.

I was using v1.0.10 of the mod enabler with v2.0.12 of Factorio Space Age, and noticed when I finally got the "Rush to Space" & "Research with production" achievements in-game they didn't unlock for Steam. Then I realized I needed to update the mod enabler, so I downloaded v1.0.12 and loaded the game back up. Even though I loaded my most recent save, which was after I had already unlocked those 2 achievements in-game, they both popped up in Steam achievements (as well as the "Visit Gleba" steam achievement, which I hadn't noticed never unlocked for Steam until then).

I don't think I've unlocked any new in-game achievements since then, so I don't know whether or not the mod enabler is still working properly on the current public game version.

**Comment by oorzkws** [comment]
I'm going to make a few test scenarios and see if things work how they should. I'll edit them in here as I go through it.

Each is started by locking the achievement "Automate this!" in Steam Achievement Manager.

Test 1: **Success**. Launched the game with FAE active.
![image](https://github.com/user-attachments/assets/f6339e06-c9e4-4d4a-813a-0beae590a015)

Test 2: **Pending** Deleted achievements.dat and then launched the game with FAE active, then loaded a save where I had gotten this achievement.

**Comment by oorzkws** [comment]
> right before posting last night i unlocked "Rush to space" and "Logistic network embargo" but now i dont get the achievement on steam. i have a savegame right before researching my first fulgora research.
> 
> i kept 2.0.11 the last couple days because steam achievements worked with 1.0.11 then i updated to 2.0.12 with 1.0.12 patches and played until i unlocked the above mentioned achievements but steam did not recognize them. maybe the steam achievement doesnt get triggered because i already earned it ingame?

If you earned the achievement without the enabler active and then loaded the game with it active, the achievement won't be retroactively unlocked on Steam. The game keeps achievements in separate files (achievements.dat, achievements-modded.dat) and loads a different on if vanilla or modded+FAE versus regular modded.

However, if you're earning the new achievement with FAE active, it should immediately unlock on Steam as well.

**Comment by Ioney** [comment]
i always had the version.dll "installed".
first i used v1.0.10 with factorio v2.0.10.
then updated to v1.0.11 and factorio v2.0.11.
played for some days and earned some achievements which were also unlocked on steam

i saw that v1.0.12 was already released, also updated factorio to v2.0.12 and earned both the achievements, but they were not unlocked

i deleted the achievements.dat and achievements-modded.dat file, but it doesnt unlock the steam achievement.
![image](https://github.com/user-attachments/assets/0979de4c-c1d4-4e9d-b484-860852c58a33)
![image](https://github.com/user-attachments/assets/772d683b-c24f-4f4b-a81d-3fc0ad7e684c)
![image](https://github.com/user-attachments/assets/61ddf5d9-ce22-4ec1-b9cc-f92978b6f113)

is there a bug in my save? should i try to start a new game?

**Comment by oorzkws** [comment]
If you'd like to upload your save somewhere, I can look and see if there's something weird with it. Does the achievements UI (list) in game show the modded warning?

**Comment by Ioney** [comment]
never looked at that before but yes it does say its modded

**Comment by oorzkws** [comment]
> never looked at that before but yes it does say its modded

Okay, so the bypass isn't being loaded into your game. Did you add the launch options in steam as the readme instructs?

**Comment by Ioney** [comment]
yes, it is set. always since i first used the enabler.

**Comment by oorzkws** [comment]
Does the .dll have a security warning in the properties?
![image](https://github.com/user-attachments/assets/13e239b3-226c-470d-9691-bc33b493ffce)

**Comment by ouchie3014** [comment]
Mine also stopped working recently. Last achievement was Oct. 25, and definitely should have had a few more after that, but they are not showing up on steam.

Was using an older version of the dll from a several months ago (didn't update since it was working fine). Then I realized today that the achievements stopped working. I updated to the latest dll but that didn't fix it. Currently on latest dll and latest factorio and standing on Fulgora but that achievement (Travel to Fulgora) is still showing as locked.

**Comment by oorzkws** [comment]
@ouchie3014 does your achievement list in-game have a mod warning?

**Comment by Ioney** [comment]
> Does the .dll have a security warning in the properties? ![image](https://private-user-images.githubusercontent.com/65210810/382432752-13e239b3-226c-470d-9691-bc33b493ffce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzM3NDIsIm5iZiI6MTczMDU3MzQ0MiwicGF0aCI6Ii82NTIxMDgxMC8zODI0MzI3NTItMTNlMjM5YjMtMjI2Yy00NzBkLTk2OTEtYmMzM2I0OTNmZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE4NTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NDdhYTVjZWYwMmU5OWEzN2I3YjRmYTdjYjQ5ZDg2NTExNDVhMjgyMDQ2YWFmMmUwYTA1ZWI5NGE0M2EyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZG0GFMpWj7Gff3I9bcEriUZipRCdAsRXXcjGkbXCX3Q)

no its not locked

**Comment by oorzkws** [comment]
It looks like the .dll isn't getting loaded for you. Just out of curiosity, have you rebooted since you opened this issue?

Can you create a file in the same folder as factorio.exe named `steam_appid.txt`, then open it and write `427520` and hit save.
![image](https://github.com/user-attachments/assets/54a9b430-a6b6-4af2-b78a-98043d31f276)
Once you've done that, double click factorio.exe and see if the achievements window has the same warning when it opens.

**Comment by AntNAF** [comment]
Been watching this issue, but just adding that my friend and I also have the same issue starting on .13 update on Oct 25

**Comment by ouchie3014** [comment]
> @ouchie3014 does your achievement list in-game have a mod warning?

No, I don't have that warning in-game.

My log dump if interested:

Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 41996276]: 00007ff791370000 ~ 00007ff793b7cff4
Apply Patch at 00007ff791503be9
Patched 1 of 7.
RuleSize: 20		ReplSize: 8
Search range[size: 41996268]: 00007ff791370000 ~ 00007ff793b7cfec
Apply Patch at 00007ff7914e409f
Apply Patch at 00007ff79162ce8c
Apply Patch at 00007ff792148ad3
Apply Patch at 00007ff792148b70
Patched 2 of 7.
RuleSize: 10		ReplSize: 4
Search range[size: 41996278]: 00007ff791370000 ~ 00007ff793b7cff6
Apply Patch at 00007ff7914e3ff3
Patched 3 of 7.
RuleSize: 18		ReplSize: 8
Search range[size: 41996270]: 00007ff791370000 ~ 00007ff793b7cfee
Apply Patch at 00007ff791a15d39
Patched 4 of 7.
RuleSize: 13		ReplSize: 7
Search range[size: 41996275]: 00007ff791370000 ~ 00007ff793b7cff3
Apply Patch at 00007ff79214a87b
Patched 5 of 7.
RuleSize: 14		ReplSize: 14
Search range[size: 41996274]: 00007ff791370000 ~ 00007ff793b7cff2
Apply Patch at 00007ff792148cc0
Patched 6 of 7.
RuleSize: 15		ReplSize: 13
Search range[size: 41996273]: 00007ff791370000 ~ 00007ff793b7cff1
Apply Patch at 00007ff791d6cf7b
Patched 7 of 7.
   0.000 Initializing Steam API.
   0.000 Steam requires game restart, restarting...
All done.
==============================================

**Comment by Ioney** [comment]
i reinstalled the game and loaded the savegame before the research. the message is now gone, but still no steam achievements

**Comment by ouchie3014** [comment]
Just did a few tests today and successfully got several achievements in game and in steam. So it seems like everything is working now. As far as I know nothing changed on my end. Factorio 2.0.14, dll version 1.0.12

**Comment by oorzkws** [comment]
Okay with two positives I'm going to close this, I spent a bunch of time going through the byte patches and I don't see anything it's missing on the game side.

Hopefully things are smoother from here, thanks for the patience.
