### ISSUE TITLE
Didn't work for 1.1.59

### ISSUE THREAD

**Issue by PyroGenesis** [oorzkws/FactorioAchievementEnabler#4]
Hello, I'm playing 1.1.59 but the patch didn't work for me. This is the content of my log file:
```
Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: D:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 31145972]: 00007ff6badc0000 ~ 00007ff6bcb73ff4
Apply Patch at 00007ff6baf1cf3a
Patched 1 of 6.
RuleSize: 32		ReplSize: 4
Search range[size: 31145952]: 00007ff6badc0000 ~ 00007ff6bcb73fe0
Apply Patch at 00007ff6baeffecb
Apply Patch at 00007ff6baefff6b
Patched 2 of 6.
RuleSize: 9		ReplSize: 5
Search range[size: 31145975]: 00007ff6badc0000 ~ 00007ff6bcb73ff7
Apply Patch at 00007ff6bb2e4adc
Patched 3 of 6.
RuleSize: 14		ReplSize: 8
Search range[size: 31145970]: 00007ff6badc0000 ~ 00007ff6bcb73ff2
Apply Patch at 00007ff6bb8e45ea
Patched 4 of 6.
RuleSize: 23		ReplSize: 11
Search range[size: 31145961]: 00007ff6badc0000 ~ 00007ff6bcb73fe9
Apply Patch at 00007ff6bb8e2b20
Apply Patch at 00007ff6bb8e2bcd
Patched 5 of 6.
RuleSize: 14		ReplSize: 14
Search range[size: 31145970]: 00007ff6badc0000 ~ 00007ff6bcb73ff2
Apply Patch at 00007ff6bb8e2d60
Patched 6 of 6.
   0.000 Initializing Steam API.
   0.000 Steam requires game restart, restarting...
All done.
==============================================
```

**Comment by oorzkws** [comment]
I see the issue, Steam seems to change the search order for .dlls when you launch. To resolve this, please do the following

1. Open your steam library
2. Right click Factorio
3. Click Properties
4. In the General tab, enter the following in Launch Options: `cmd /c start %command%`
5. Close the properties window

![image](https://user-images.githubusercontent.com/65210810/175927310-2eb367b0-f936-41e8-839e-60f6d7caeaf2.png)

This should resolve the issue when starting the game directly through Steam.

**Comment by Godzila543** [comment]
When I enter those commands into the launch options, it only opens a console window pathed to the game folder. The game doesn't appear to open at all. When generating a log file, the game does open and achievements sync correctly. Im on win 11 if thats anything. Also heres the log incase its useful at all.

Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 31178740]: 00007ff60d8e0000 ~ 00007ff60f69bff4
Apply Patch at 00007ff60da3d59a
Patched 1 of 6.
RuleSize: 32		ReplSize: 4
Search range[size: 31178720]: 00007ff60d8e0000 ~ 00007ff60f69bfe0
Apply Patch at 00007ff60da2052b
Apply Patch at 00007ff60da205cb
Patched 2 of 6.
RuleSize: 9		ReplSize: 5
Search range[size: 31178743]: 00007ff60d8e0000 ~ 00007ff60f69bff7
Apply Patch at 00007ff60de0679c
Patched 3 of 6.
RuleSize: 14		ReplSize: 8
Search range[size: 31178738]: 00007ff60d8e0000 ~ 00007ff60f69bff2
Apply Patch at 00007ff60e40807a
Patched 4 of 6.
RuleSize: 23		ReplSize: 11
Search range[size: 31178729]: 00007ff60d8e0000 ~ 00007ff60f69bfe9
Apply Patch at 00007ff60e4065b0
Apply Patch at 00007ff60e40665d
Patched 5 of 6.
RuleSize: 14		ReplSize: 14
Search range[size: 31178738]: 00007ff60d8e0000 ~ 00007ff60f69bff2
Apply Patch at 00007ff60e4067f0
Patched 6 of 6.
   0.000 Initializing Steam API.
   0.000 2022-08-05 14:13:06; Factorio 1.1.61 (build 59839, win64, steam)
   0.000 Operating system: Windows 10 (build 22622) 
   0.000 Program arguments: "factorio.exe" 
   0.000 Read data path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/data
   0.000 Write data path: C:/Users/colin/AppData/Roaming/Factorio [1256126/1907006MB]
   0.000 Binaries path: C:/Program Files (x86)/Steam/steamapps/common/Factorio/bin
   0.004 System info: [CPU: 12th Gen Intel(R) Core(TM) i7-12700KF, 20 cores, RAM: 10631/24389 MB, page: 15558/27973 MB, virtual: 4350/134217727 MB, extended virtual: 0 MB]
   0.005 Display options: [FullScreen: 1] [VSync: 1] [UIScale: custom (125.0%)] [Native DPI: 1] [Screen: 255] [Special: lmw] [Lang: en]
   0.008 Available displays: 3
   0.008  [2]: \\.\DISPLAY3 - NVIDIA GeForce RTX 3070 Ti {0x05, [0,0], 2560x1440, 32bit, 155Hz}
   0.008  [0]: \\.\DISPLAY1 - NVIDIA GeForce RTX 3070 Ti {0x01, [-2560,0], 2560x1440, 32bit, 59Hz}
   0.008  [1]: \\.\DISPLAY2 - NVIDIA GeForce RTX 3070 Ti {0x01, [2560,0], 2560x1440, 32bit, 59Hz}
   0.049 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
   0.139 Initialised Direct3D[0]: NVIDIA GeForce RTX 3070 Ti; id: 10de-2482; driver: nvldumdx.dll 30.0.15.1179
   0.139   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 3,flip-discard,-,-,-,none
   0.139   [Local Video Memory] Budget: 7274MB, CurrentUsage: 4MB, Reservation: 0/3765MB
   0.139   [Non-Local Vid.Mem.] Budget: 11426MB, CurrentUsage: 0MB, Reservation: 0/5841MB
   0.139   Tiled resources: Tier 2
   0.139   Unified Memory Architecture: No
   0.139   BGR 565 Supported: Yes
   0.139   MaximumFrameLatency: 3, GPUThreadPriority: 0
   0.139 Graphics settings preset: very-high
   0.139   Dedicated video memory size 8042 MB
   0.166 Desktop composition is active.
   0.166 Graphics options: [Graphics quality: high] [Video memory usage: all] [DXT: high-quality] [Color: 32bit]
   0.166                   [Max threads (load/render): 32/20] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: normal] [Other: STDCWT] [B:0,C:0,S:100]
   0.195 DSound: Starting _dsound_update thread
   0.195 [Audio] Backend:default; Depth:16, Channel:2, Frequency:44100; MixerQuality:linear
   0.196 DSound: Enter _dsound_update; tid=13024
   0.279 Loading mod settings even-distribution 1.0.10 (settings.lua)
   0.280 Loading mod settings far-reach 1.1.2 (settings.lua)
   0.280 Loading mod settings flib 0.10.1 (settings.lua)
   0.280 Loading mod settings Squeak Through 1.8.2 (settings.lua)
   0.280 Loading mod settings factoryplanner 1.1.51 (settings.lua)
   0.281 Loading mod core 0.0.0 (data.lua)
   0.313 Loading mod base 1.1.61 (data.lua)
   0.429 Loading mod AfraidOfTheDark 1.1.1 (data.lua)
   0.437 Loading mod DiscoScience 1.1.3 (data.lua)
   0.443 Loading mod even-distribution 1.0.10 (data.lua)
   0.449 Loading mod flib 0.10.1 (data.lua)
   0.455 Loading mod factoryplanner 1.1.51 (data.lua)
   0.461 Loading mod base 1.1.61 (data-updates.lua)
   0.467 Loading mod AfraidOfTheDark 1.1.1 (data-updates.lua)
   0.473 Loading mod Squeak Through 1.8.2 (data-updates.lua)
   0.480 Loading mod AfraidOfTheDark 1.1.1 (data-final-fixes.lua)
   0.529 Checksum for core: 1720724266
   0.529 Checksum of base: 2195340303
   0.529 Checksum of AfraidOfTheDark: 2330519148
   0.529 Checksum of DiscoScience: 1542355472
   0.529 Checksum of even-distribution: 3296431338
   0.529 Checksum of far-reach: 3717351288
   0.529 Checksum of flib: 2594110821
   0.529 Checksum of Squeak Through: 2759453103
   0.529 Checksum of factoryplanner: 453284339
   0.646 Prototype list checksum: 1597908806
   0.673 Loading sounds...
   0.740 Info PlayerData.cpp:73: Local player-data.json unavailable
   0.740 Info PlayerData.cpp:76: Cloud player-data.json available, timestamp 1659733899
   0.828 Initial atlas bitmap size is 16384
   0.856 Created atlas bitmap 16384x16376 [none]
   0.859 Created atlas bitmap 16384x13060 [none]
   0.859 Created atlas bitmap 8192x4188 [decal]
   0.860 Created atlas bitmap 16384x5568 [low-object, linear-minification]
   0.860 Created atlas bitmap 8192x4272 [mipmap, linear-minification, linear-magnification, linear-mip-level]
   0.861 Created atlas bitmap 16384x6064 [terrain, mipmap, linear-minification, linear-mip-level]
   0.861 Created atlas bitmap 4096x3216 [terrain-effect-map, mipmap, linear-minification, linear-mip-level]
   0.861 Created atlas bitmap 4096x1856 [smoke, mipmap, linear-minification, linear-magnification]
   0.861 Created atlas bitmap 4096x3104 [mipmap]
   0.862 Created atlas bitmap 8192x2320 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
   0.862 Created atlas bitmap 8192x1496 [alpha-mask]
   0.864 Created atlas bitmap 16384x14768 [shadow, linear-magnification, alpha-mask]
   0.864 Created atlas bitmap 8192x2352 [shadow, mipmap, linear-magnification, alpha-mask]
   0.865 Created atlas bitmap 2048x240 [icon-background, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level, ]
   0.867 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
   1.341 Parallel Sprite Loader initialized (threads: 19)
   6.753 Sprites loaded
   6.765 Generated mipmaps (4) for atlas [3] of size 16384x5568   
   6.776 Generated mipmaps (3) for atlas [4] of size 8192x4272   
   6.798 Generated mipmaps (3) for atlas [5] of size 16384x6064   
   6.819 Generated mipmaps (3) for atlas [6] of size 4096x3216   
   6.831 Generated mipmaps (3) for atlas [7] of size 4096x1856   
   6.871 Generated mipmaps (3) for atlas [8] of size 4096x3104   
   6.882 Generated mipmaps (5) for atlas [9] of size 8192x2320   
   6.893 Generated mipmaps (3) for atlas [12] of size 8192x2352   
   6.905 Custom mipmaps uploaded.
   6.911 Custom inputs active: 12
   7.058 Factorio initialised
   7.058 Discord overlay detected (DiscordHook64.dll)
   7.060 Steam Storage Quota: 4725/4768
  13.941 Loading map C:\Users\colin\AppData\Roaming\Factorio\saves\day4.zip: 8923167 bytes.
  13.960 Loading level.dat: 20679964 bytes.
  13.963 Info Scenario.cpp:199: Map version 1.1.61-0
  14.152 Loading script.dat: 417684 bytes.
  14.155 Checksum for script C:/Users/colin/AppData/Roaming/Factorio/temp/currently-playing/control.lua: 3795083680
  14.155 Checksum for script __AfraidOfTheDark__/control.lua: 2322376383
  14.157 Checksum for script __DiscoScience__/control.lua: 3734133783
  14.157 Script @__even-distribution__/framework.lua:72: 0 [ED] Initializing framework... DEBUG = false
  14.157 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering custom scripts...
  14.157 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: metatables
  14.157 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: util
  14.158 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: helpers
  14.158 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: setup
  14.158 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: remote
  14.158 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: visuals
  14.159 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: gui-tools
  14.159 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: drag
  14.159 Script @__even-distribution__/framework.lua:72: 0 [ED] Script: cleanup
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] GUI-Script: settings-gui
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering default event handlers...
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] Registering custom inputs...
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: inventory-cleanup   event: on_inventory_cleanup
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: fast-entity-transfer-hook   event: on_fast_entity_transfer_hook
  14.160 Script @__even-distribution__/framework.lua:72: 0 [ED] Input: fast-entity-split-hook   event: on_fast_entity_split_hook
  14.161 Script @__even-distribution__/framework.lua:72: 0 [ED] Successfully initialized
  14.161 Checksum for script __even-distribution__/control.lua: 850894597
  14.162 Checksum for script __far-reach__/control.lua: 2302075386
  14.177 Checksum for script __factoryplanner__/control.lua: 1123091946
  16.873 Unlocked achievement "circuit-veteran-1"
  16.873 Unlocked achievement "iron-throne-1"
  26.179 Quitting: user-quit.
  26.232 DSound: Stopping voice
  26.232 DSound: Joining thread
  26.233 DSound: Exit _dsound_update; tid=13024
  26.233 DSound: Waiting for voice to stop ... signaled
  26.233 DSound: Joined thread
  26.233 DSound: Destroying thread
  26.233 DSound: Thread destroyed
  26.233 DSound: Releasing buffer
  26.233 DSound: Voice stopped
  26.233 DSound: Deallocating voice
  26.233 DSound: Deallocated voice
  26.260 Steam API shutdown.
  26.264 Goodbye
All done.
==============================================

**Comment by oorzkws** [comment]
@Godzila543 I'm not 100% sure then, the issue is that steam overrides some stuff when you launch through steam. If you launch outside of steam (but using the game installed from steam) it works fine. I haven't really figured out why it's doing that besides steam overriding some environmental stuff.

**Comment by oorzkws** [comment]
Ah, looks like it may be `cmd /c "start %command%"` if you could try that

**Comment by cjames11** [comment]
@oorzkws I have the same issue. The log output file is the same as @Godzila543, the patch seems to be applied successfully, but the game wouldn't launch and instead opens a cmd with a path to the game folder. This happens both when the game is launched directly from steam or using the factorio exe. I've tried both cmd /c "start %command%" and cmd /c start %command%

**Comment by cjames11** [comment]
@oorzkws I got a workaround - once the cmd window opens after launch, simply change directory to the bin folder & launch factorio.exe again. Achievements are synced! Many thanks for your work

**Comment by oorzkws** [comment]
> @oorzkws I got a workaround - once the cmd window opens after launch, simply change directory to the bin folder & launch factorio.exe again. Achievements are synced! Many thanks for your work

I'm glad to hear that at least works. Do you mind if I ask what directory it drops you in initially?

**Comment by cjames11** [comment]
@oorzkws it was C:\Program Files (x86)\Steam\steamapps\common\Factorio
