### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ArtStepanyuk** [oorzkws/FactorioAchievementEnabler#5]
I just wanted to say thanks for your work. Factorio is a great game but I almost gave up on it on 1st hour of the game. There are QOL mods that pretty much should be in base game and weird decision about turning achievements off cause of that was just plain stupid.

Now I'm over 70 hours in :)

Thank you again

**Comment by oorzkws** [comment]
Thanks for the kind note, you improved my day. I'm happy to hear this is being used by someone other than myself :)
