### ISSUE TITLE
Not working in 1.1.68

### ISSUE THREAD

**Issue by rsttls** [oorzkws/FactorioAchievementEnabler#6]
Steam Achievements not working...
Tried launching it from steam and the exe file, nothing.

Output:
Fixing import for version.dll...
StartPatch called...
do_patch called...
szExePath: C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe
RuleSize: 12		ReplSize: 11
Search range[size: 31399924]: 00007ff66edb0000 ~ 00007ff670ba1ff4
Didn't patch 1 of 6.
RuleSize: 32		ReplSize: 4
Search range[size: 31399904]: 00007ff66edb0000 ~ 00007ff670ba1fe0
Apply Patch at 00007ff66eef05c3
Apply Patch at 00007ff66eef065e
Patched 2 of 6.
RuleSize: 9		ReplSize: 5
Search range[size: 31399927]: 00007ff66edb0000 ~ 00007ff670ba1ff7
Apply Patch at 00007ff66f2d637b
Patched 3 of 6.
RuleSize: 14		ReplSize: 8
Search range[size: 31399922]: 00007ff66edb0000 ~ 00007ff670ba1ff2
Didn't patch 4 of 6.
RuleSize: 23		ReplSize: 11
Search range[size: 31399913]: 00007ff66edb0000 ~ 00007ff670ba1fe9
Apply Patch at 00007ff66f8dc130
Apply Patch at 00007ff66f8dc1dd
Patched 5 of 6.
RuleSize: 14		ReplSize: 14
Search range[size: 31399922]: 00007ff66edb0000 ~ 00007ff670ba1ff2
Apply Patch at 00007ff66f8dc370
Patched 6 of 6.
   0.000 Initializing Steam API.
   0.000 Steam requires game restart, restarting...
All done.
==============================================

**Comment by oorzkws** [comment]
Resolved in [v1.0.4](https://github.com/oorzkws/FactorioAchievementEnabler/releases/tag/v1.0.4)

**Comment by rsttls** [comment]
Thank you
