### ISSUE TITLE
Command line and no game

### ISSUE THREAD

**Issue by satoon10** [oorzkws/FactorioAchievementEnabler#7]
After placing the .dll and the Launch Options, when opening the game the command line opens up, and nothing else.
![](https://i.imgur.com/iJhFwqf.png)

**Comment by oorzkws** [comment]
does `cmd /c start %command%\bin\x64\factorio.exe` as the launch option work?

**Comment by satoon10** [comment]
> does `cmd /c start %command%\bin\x64\factorio.exe` as the launch option work?

Nope, command line opens again.

**Comment by oorzkws** [comment]
That's very odd behavior considering we're literally just running a program. I'm not sure on this one. Does it behave the same if you go into the Factorio folder and just run the .exe?

**Comment by satoon10** [comment]
Opening from the .exe still gets me the command line, it will only run the game without the Launch Options.

**Comment by oorzkws** [comment]
Okay, that's interesting. Would you be able to generate a log like explained here: https://github.com/oorzkws/FactorioAchievementEnabler#notes

I'm wondering if one of the patches is hitting where it shouldn't be

**Comment by satoon10** [comment]
> Would you be able to generate a log like explained here: https://github.com/oorzkws/FactorioAchievementEnabler#notes

Am I doing something wrong? Because all I get is "Acess Denied"
`C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe > C:\Users\PC\Desktop`

**Comment by oorzkws** [comment]
> > Would you be able to generate a log like explained here: https://github.com/oorzkws/FactorioAchievementEnabler#notes
> 
> Am I doing something wrong? Because all I get is "Acess Denied" `C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe > C:\Users\PC\Desktop`

it would be `C:\Program Files (x86)\Steam\steamapps\common\Factorio\bin\x64\factorio.exe > C:\Users\PC\Desktop\output.txt`

**Comment by oorzkws** [comment]
Ah, and one other question - do the launch arguments in steam work without the version.dll present in the bin\x64 folder?

**Comment by satoon10** [comment]
Without the version.dll the command line still opens up.

**Comment by jsteph262** [comment]
I'm having this same issue. When I try to make a log it just comes up blank.

**Comment by oorzkws** [comment]
Oh man, I've made a very elementary mistake reading the docs for `start`. Give the following a try and let me know if it works:
`cmd /c start "" %command%`
![image](https://user-images.githubusercontent.com/65210810/189897424-3073f414-e9e3-4312-8a7a-1dfb00d139f6.png)

**Comment by satoon10** [comment]
> Oh man, I've made a very elementary mistake reading the docs for `start`. Give the following a try and let me know if it works: `cmd /c start "" %command%` ![image](https://user-images.githubusercontent.com/65210810/189897424-3073f414-e9e3-4312-8a7a-1dfb00d139f6.png)

Works perfectly, thank you!

**Comment by djchill1** [comment]
> Oh man, I've made a very elementary mistake reading the docs for `start`. Give the following a try and let me know if it works: `cmd /c start "" %command%` !

Can you update this in the readme.md too? It still shows the version without the quotes.

**Comment by oorzkws** [comment]
> Can you update this in the readme.md too? It still shows the version without the quotes.

> Grab the latest from [releases](https://github.com/oorzkws/FactorioAchievementEnabler/releases) and place the version.dll in the same folder as your Factorio.exe (Factorio\bin\x64). In Steam, add cmd /c start "" %command% as the launch options under the game properties.

Did I miss a second place somewhere?

**Comment by djchill1** [comment]
Ah you're correct it has now updated. Thank you for your reply and efforts
creating and sharing! :)
