### ISSUE TITLE
Didn't patch 3 of 6. (v1.1.74)

### ISSUE THREAD

**Issue by jondck** [oorzkws/FactorioAchievementEnabler#9]
I got this from log:
Apply Patch at 00007ff7d92f0e03
Apply Patch at 00007ff7d92f0e9e
Patched 2 of 6.
Unexpected char: 0x48
Didn't patch 3 of 6.

The rest were ok.

**Comment by oorzkws** [comment]
Thanks for the report, this is fixed in [releases/v1.0.6](https://github.com/oorzkws/FactorioAchievementEnabler/releases/latest)
